# NumPy for Numerical Data Analysis

## Objective
This notebook demonstrates the fundamentals of **NumPy** and its use in numerical data analysis.

### Topics Covered
- Creating 1D, 2D, and 3D arrays
- Array dimensions, shape, size, and data type
- Indexing and slicing
- Reshaping arrays
- Array creation functions: `zeros()`, `ones()`, `arange()`, `linspace()`
- Mathematical and vectorized operations
- Boolean masking
- Broadcasting
- Aggregate functions: `sum()`, `mean()`, `min()`, `max()`, and `median()`


## 1. Import NumPy

In [1]:
import numpy as np

print("NumPy version:", np.__version__)


NumPy version: 2.1.3


## 2. Creating a 1D Array

In [2]:
# A one-dimensional array
array_1d = np.array([10, 20, 30, 40, 50])

print("1D Array:", array_1d)
print("Number of dimensions:", array_1d.ndim)
print("Shape:", array_1d.shape)
print("Size:", array_1d.size)
print("Data type:", array_1d.dtype)


1D Array: [10 20 30 40 50]
Number of dimensions: 1
Shape: (5,)
Size: 5
Data type: int64


## 3. Creating a 2D Array

In [3]:
# A two-dimensional array (matrix)
array_2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("2D Array:")
print(array_2d)
print("Number of dimensions:", array_2d.ndim)
print("Shape:", array_2d.shape)
print("Size:", array_2d.size)
print("Data type:", array_2d.dtype)


2D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Number of dimensions: 2
Shape: (3, 3)
Size: 9
Data type: int64


## 4. Creating a 3D Array

In [4]:
# A three-dimensional array
array_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])

print("3D Array:")
print(array_3d)
print("Number of dimensions:", array_3d.ndim)
print("Shape:", array_3d.shape)
print("Size:", array_3d.size)
print("Data type:", array_3d.dtype)


3D Array:
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Number of dimensions: 3
Shape: (3, 2, 2)
Size: 12
Data type: int64


## 5. Checking Array Dimensions and Data Types

In [5]:
numbers = np.array([1, 2, 3, 4, 5], dtype=np.float64)

print("Array:", numbers)
print("Dimensions:", numbers.ndim)
print("Shape:", numbers.shape)
print("Number of elements:", numbers.size)
print("Data type:", numbers.dtype)


Array: [1. 2. 3. 4. 5.]
Dimensions: 1
Shape: (5,)
Number of elements: 5
Data type: float64


## 6. Indexing

In [6]:
array = np.array([10, 20, 30, 40, 50])

print("First element:", array[0])
print("Third element:", array[2])
print("Last element:", array[-1])


First element: 10
Third element: 30
Last element: 50


## 7. Indexing in a 2D Array

In [7]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Element at row 1, column 2:", matrix[1, 2])
print("First row:", matrix[0])
print("Second column:", matrix[:, 1])


Element at row 1, column 2: 60
First row: [10 20 30]
Second column: [20 50 80]


## 8. Slicing

In [8]:
array = np.array([10, 20, 30, 40, 50, 60])

print("Elements from index 1 to 4:", array[1:5])
print("First three elements:", array[:3])
print("Elements from index 3:", array[3:])
print("Every second element:", array[::2])


Elements from index 1 to 4: [20 30 40 50]
First three elements: [10 20 30]
Elements from index 3: [40 50 60]
Every second element: [10 30 50]


## 9. Slicing a 2D Array

In [9]:
matrix = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print("First two rows:")
print(matrix[:2])

print("\nFirst two columns:")
print(matrix[:, :2])

print("\nRows 1-2 and columns 2-3:")
print(matrix[1:, 2:])


First two rows:
[[10 20 30 40]
 [50 60 70 80]]

First two columns:
[[ 10  20]
 [ 50  60]
 [ 90 100]]

Rows 1-2 and columns 2-3:
[[ 70  80]
 [110 120]]


## 10. Reshaping Arrays

In [10]:
array = np.arange(1, 13)

print("Original array:")
print(array)

reshaped = array.reshape(3, 4)

print("\nReshaped into 3 x 4:")
print(reshaped)
print("New shape:", reshaped.shape)


Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped into 3 x 4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
New shape: (3, 4)


## 11. Array Creation Functions

In [11]:
# zeros()
zeros_array = np.zeros((2, 3))

# ones()
ones_array = np.ones((2, 3))

# arange()
range_array = np.arange(0, 10, 2)

# linspace()
linear_array = np.linspace(0, 1, 6)

print("zeros():")
print(zeros_array)

print("\nones():")
print(ones_array)

print("\narange():")
print(range_array)

print("\nlinspace():")
print(linear_array)


zeros():
[[0. 0. 0.]
 [0. 0. 0.]]

ones():
[[1. 1. 1.]
 [1. 1. 1.]]

arange():
[0 2 4 6 8]

linspace():
[0.  0.2 0.4 0.6 0.8 1. ]


## 12. Mathematical Operations

In [12]:
a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Power:", a ** 2)


Addition: [12 24 35 48]
Subtraction: [ 8 16 25 32]
Multiplication: [ 20  80 150 320]
Division: [5. 5. 6. 5.]
Power: [ 100  400  900 1600]


## 13. Vectorized Operations

In [13]:
# NumPy performs operations on entire arrays without explicit Python loops
marks = np.array([45, 60, 72, 85, 90])

bonus_marks = marks + 5
percentage = marks / 100
squared_marks = marks ** 2

print("Original marks:", marks)
print("Marks after adding 5:", bonus_marks)
print("Percentage representation:", percentage)
print("Squared marks:", squared_marks)


Original marks: [45 60 72 85 90]
Marks after adding 5: [50 65 77 90 95]
Percentage representation: [0.45 0.6  0.72 0.85 0.9 ]
Squared marks: [2025 3600 5184 7225 8100]


## 14. Boolean Masking

In [14]:
marks = np.array([35, 48, 55, 67, 72, 81, 90])

# Create a Boolean condition
passed = marks >= 50

print("Marks:", marks)
print("Pass condition:", passed)
print("Passing marks:", marks[passed])

# Direct boolean masking
print("Marks greater than 70:", marks[marks > 70])


Marks: [35 48 55 67 72 81 90]
Pass condition: [False False  True  True  True  True  True]
Passing marks: [55 67 72 81 90]
Marks greater than 70: [72 81 90]


## 15. Broadcasting

In [15]:
# Broadcasting allows NumPy to perform operations
# between arrays of compatible shapes.

marks = np.array([
    [60, 70, 80],
    [65, 75, 85],
    [70, 80, 90]
])

bonus = np.array([5, 10, 15])

result = marks + bonus

print("Original marks:")
print(marks)

print("\nBonus marks:")
print(bonus)

print("\nResult after broadcasting:")
print(result)


Original marks:
[[60 70 80]
 [65 75 85]
 [70 80 90]]

Bonus marks:
[ 5 10 15]

Result after broadcasting:
[[ 65  80  95]
 [ 70  85 100]
 [ 75  90 105]]


## 16. Aggregate Functions

In [16]:
data = np.array([10, 20, 30, 40, 50, 60])

print("Data:", data)
print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Median:", np.median(data))


Data: [10 20 30 40 50 60]
Sum: 210
Mean: 35.0
Minimum: 10
Maximum: 60
Median: 35.0


## 17. Aggregate Functions on a 2D Array

In [17]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Matrix:")
print(matrix)

print("\nTotal sum:", np.sum(matrix))
print("Mean:", np.mean(matrix))
print("Minimum:", np.min(matrix))
print("Maximum:", np.max(matrix))
print("Median:", np.median(matrix))

print("\nColumn-wise sum:", np.sum(matrix, axis=0))
print("Row-wise sum:", np.sum(matrix, axis=1))


Matrix:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Total sum: 450
Mean: 50.0
Minimum: 10
Maximum: 90
Median: 50.0

Column-wise sum: [120 150 180]
Row-wise sum: [ 60 150 240]


## 18. Mini Numerical Data Analysis Example

In [18]:
# Student marks analysis using NumPy
student_marks = np.array([78, 85, 92, 67, 88, 74, 95, 81, 69, 90])

print("Student Marks:", student_marks)
print("Total Marks:", np.sum(student_marks))
print("Average Marks:", np.mean(student_marks))
print("Minimum Marks:", np.min(student_marks))
print("Maximum Marks:", np.max(student_marks))
print("Median Marks:", np.median(student_marks))

# Students scoring above the average
average = np.mean(student_marks)
above_average = student_marks[student_marks > average]

print("\nAverage:", average)
print("Marks above average:", above_average)
print("Number of students above average:", above_average.size)


Student Marks: [78 85 92 67 88 74 95 81 69 90]
Total Marks: 819
Average Marks: 81.9
Minimum Marks: 67
Maximum Marks: 95
Median Marks: 83.0

Average: 81.9
Marks above average: [85 92 88 95 90]
Number of students above average: 5


## 19. Conclusion

In this notebook, we demonstrated how NumPy can be used for numerical data analysis.

### Key Takeaways
- NumPy provides efficient **1D, 2D, and 3D arrays**.
- Array properties such as `ndim`, `shape`, `size`, and `dtype` help understand array structure.
- **Indexing and slicing** provide easy access to array elements.
- `reshape()` changes an array's structure without changing its data.
- `zeros()`, `ones()`, `arange()`, and `linspace()` simplify array creation.
- NumPy supports fast **mathematical and vectorized operations**.
- **Boolean masking** helps filter data based on conditions.
- **Broadcasting** allows operations between compatible arrays of different shapes.
- Aggregate functions such as `sum()`, `mean()`, `min()`, `max()`, and `median()` make numerical analysis simple.
